[package]
name = "d_sci"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
ndarray = { version = "0.16.1", features = ["rayon", "serde"] }
ndarray-parallel = "0.9.1"
serde = { version = "1.0.209", features = ["derive"] }
