[workspace]

members = [ "closures", "collections", "csv_read", "enumin", "generico",
    "guesser", "handlin_error",
    "listerator", "ooping", "owningrs", "pkg", "restaurant", "serde_use", "structs", "testit", "traito", "web_reqs",
]
resolver = "2"
