[package]
name = "sqlx_with_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.0", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
