[package]
name = "rust-io"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
tokio = { version = "1.38.1", features = ["full"] }
uuid = { version = "1.10.0", features = ["v6", "v8"] }
