[package]
name = "data_vis"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
plotters = "0.3.6"
polars = { version = "0.35.0", features = ["describe", "lazy", "ndarray", "object", "dtype-struct", "concat_str", "mode"] }
