[package]
name = "lifetime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
deriver = { path = "../lgr_ws/deriver"}
hello_macro_derive = { path = "../lgr_ws/hello_macro_derive"}

